### ISSUE TITLE
checkValidDgram broadcast ACK

### ISSUE THREAD

**Issue by zeroDecoder** [Saint-Francis-Robotics-Team2367/yunServerSoftware#1]
Host::checkValidDgram sends ACK to client as broadcast instead of as a data-gram directed at the client.

**Comment by DanG100** [comment]
Intentional, just laziness on where client checks for connection, all info for connection happens on broadcast socket, but message directed to client

**Comment by zeroDecoder** [comment]
Hence the listing as an enhancement. It would be nice if it got fixed, but in the end not a big deal.

**Comment by DanG100** [comment]
fixed
